// Created by Crowbar 0.74

$modelname "p_balrog9.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "weapon"
{
	studio "p_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bip01 L Forearm" 0 -3.02 -3.25 10.762131 3.91 4.37
$hbox 0 "Bip01 L Hand" 0 -3.04 -3.74 8.22 3.69 3.07
$hbox 0 "Bip01 R Forearm" 0 -3.02 -4.37 10.762129 3.91 3.25
$hbox 0 "Bip01 R Hand" 0 -3.04 -3.07 8.4 3.69 3.74

$sequence "idle" {
	"p_balrog9_anims\idle"
	fps 30
}
