"""ReChecker rules: kick a player whose copy of our models/sprites differs.

`ReChecker <https://github.com/rehlds/ReChecker>`_ (``resources.ini``) asks
each client for a file's hash and runs a command on a match:
``"path" hash "command" FLAGS``, where *hash* is the first 8 hex digits of
the file's MD5, ``UNKNOWN`` any other hash and ``MISSING`` no file;
``IGNORE`` accepts, ``BREAK`` stops checking further files. A modified model
or sprite (see-through walls, glowing players) is the classic cheat this
stops: each file gets its true hash as ``IGNORE`` and any other as a kick.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

DEFAULT_COMMAND = "kick [userid] 'Modified file: [file_name] — delete it and reconnect'"
CHECKED = (".mdl", ".spr")


def short_hash(path: Path) -> str:
    """The 8-hex-digit MD5 prefix ReChecker compares."""
    return hashlib.md5(Path(path).read_bytes()).hexdigest()[:8]


def rules(files: dict[str, Path], *, command: str = DEFAULT_COMMAND,
          include_sounds: bool = False) -> str:
    """``resources.ini`` lines for ``{game path: file}`` (models and
    sprites; sounds too with ``include_sounds``)."""
    kinds = CHECKED + ((".wav",) if include_sounds else ())
    lines = ["; ReChecker rules for this pack — generated by valve-qc-merger Studio",
             "; the true hash is accepted, any other copy runs the command"]
    width = max((len(p) for p in files), default=20) + 4
    for game_path in sorted(files, key=str.lower):
        if not game_path.lower().endswith(kinds):
            continue
        quoted = f'"{game_path}"'.ljust(width)
        lines.append(f"{quoted}{short_hash(files[game_path])}\tIGNORE")
        lines.append(f'{quoted}UNKNOWN\t\t"{command}"\tBREAK')
    return "\n".join(lines) + "\n"


__all__ = ["CHECKED", "DEFAULT_COMMAND", "rules", "short_hash"]
