"""Unprecaching stock resources: a ``list.ini`` for Metamod Unprecacher.

`metamod_unprecacher <https://github.com/In-line/metamod_unprecacher>`_ reads
``path flags replace_path`` per line: flag ``c`` swaps the file for
``replace_path`` wherever the game asks for it (safe: entities still get a
model), ``a`` deletes entities using it, ``b`` (with ``a``) spares players.
Unprecaching a model the game still sets on an entity without a
replacement crashes clients — so a replacement is offered and recommended.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Entry:
    path: str
    replace: str = ""  # "" = block only
    delete_entities: bool = False


def slots_freed(entries: list[Entry], precached: set[str] | None = None) -> int:
    """Model slots the list frees: one per unprecached file, minus each
    replacement model that is not precached already."""
    precached = {p.lower() for p in precached or set()}
    replacements = {e.replace.lower() for e in entries if e.replace}
    blocked = {e.path.lower() for e in entries}
    return len(blocked) - len(replacements - precached - blocked)


def list_ini(entries: list[Entry], *, title: str = "") -> str:
    """The ``list.ini`` text (one entry per line, ``;`` comments)."""
    lines = ["; Metamod Unprecacher list — generated by valve-qc-merger Studio",
             "; path flags replace_path   (c: replace, a: delete entities, b: spare players)"]
    if title:
        lines.append(f"; {title}")
    for entry in entries:
        flags = ("c" if entry.replace else "") + ("a" if entry.delete_entities else "")
        line = entry.path if not flags else f"{entry.path} {flags}"
        if entry.replace:
            line += f" {entry.replace}"
        lines.append(line)
    return "\n".join(lines) + "\n"


def parse_list_ini(text: str) -> list[Entry]:
    out = []
    for raw in text.splitlines():
        line = raw.split(";", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        flags = parts[1] if len(parts) > 1 and parts[1].isalpha() and len(parts[1]) <= 3 \
            else ""
        replace = parts[2] if flags and "c" in flags and len(parts) > 2 else ""
        out.append(Entry(parts[0], replace, "a" in flags))
    return out


__all__ = ["Entry", "list_ini", "parse_list_ini", "slots_freed"]
