"""Generate a compilable QC for the exported model (Phase 5 convenience).

Beyond §7.7 (which lists only SMD outputs), a GoldSrc model still needs a QC to
compile. This rebuilds one from the input QC: the same sequences (fps + events)
and attachments, but pointing at the *merged* reference-hands+weapon mesh SMD and
the retargeted ``anims/`` set. References to bones that Phase 5 deletes (the
original arm/forearm bones used by ``$hbox``) are dropped, since those bones no
longer exist in the unified skeleton.

Pure text in, pure text out — no ``bpy``.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

_SEQ_HEAD_RE = re.compile(r'\$sequence\s+"(?P<name>[^"]+)"\s*\{')
_FPS_RE = re.compile(r"\bfps\s+(?P<fps>[0-9.]+)")
_EVENT_RE = re.compile(r"\{\s*event\b[^}]*\}")
_ATTACH_RE = re.compile(
    r'\$attachment\s+(?P<idx>\d+)\s+"(?P<bone>[^"]+)"\s+'
    r"(?P<x>\S+)\s+(?P<y>\S+)\s+(?P<z>\S+)"
)
_MODELNAME_RE = re.compile(r'\$modelname\s+"(?P<name>[^"]+)"')


@dataclass(frozen=True)
class QcSequence:
    name: str
    fps: float | None
    events: tuple[str, ...]


def _matching_brace(text: str, open_index: int) -> int:
    """Index of the ``}`` that closes the ``{`` at ``open_index`` (nesting-aware)."""
    depth = 0
    for i in range(open_index, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return i
    return len(text)


def parse_sequences(qc_text: str) -> list[QcSequence]:
    """Extract every ``$sequence`` with its fps and raw event lines, in file order.

    The body is delimited by brace matching, not a lazy regex, because a
    ``$sequence`` block contains nested ``{ event ... }`` blocks.
    """
    out: list[QcSequence] = []
    for m in _SEQ_HEAD_RE.finditer(qc_text):
        open_index = m.end() - 1
        close_index = _matching_brace(qc_text, open_index)
        body = qc_text[open_index + 1:close_index]
        fps_m = _FPS_RE.search(body)
        fps = float(fps_m.group("fps")) if fps_m else None
        events = tuple(e.strip() for e in _EVENT_RE.findall(body))
        out.append(QcSequence(m.group("name"), fps, events))
    return out


def parse_attachments(qc_text: str, surviving_bones: set[str]) -> list[str]:
    """Return ``$attachment`` lines whose bone survives into the unified skeleton."""
    kept: list[str] = []
    for m in _ATTACH_RE.finditer(qc_text):
        if m.group("bone") in surviving_bones:
            kept.append(
                f'$attachment {m.group("idx")} "{m.group("bone")}" '
                f'{m.group("x")} {m.group("y")} {m.group("z")}'
            )
    return kept


def modelname(qc_text: str, default: str) -> str:
    m = _MODELNAME_RE.search(qc_text)
    return m.group("name") if m else default


def build_qc(
    qc_text: str,
    *,
    mesh_stem: str,
    anims_subdir: str,
    surviving_bones: set[str],
    model_name: str,
) -> str:
    """Render a QC that compiles the merged mesh SMD + the retargeted animations."""
    sequences = parse_sequences(qc_text)
    attachments = parse_attachments(qc_text, surviving_bones)

    lines: list[str] = [
        "// Regenerated by valve-qc-merger (Phase 5): reference hands + weapon,",
        "// unified skeleton. Hands and weapon are merged into one reference SMD.",
        "",
        f'$modelname "{modelname(qc_text, model_name)}"',
        '$cd "."',
        '$cdtexture "."',
        "$cliptotextures",
        "$scale 1.0",
        "",
        f'$body "studio" "{mesh_stem}"',
        "",
        "$flags 0",
        "",
    ]
    for attach in attachments:
        lines.append(attach)
    if attachments:
        lines.append("")

    for seq in sequences:
        lines.append(f'$sequence "{seq.name}" {{')
        lines.append(f'\t"{anims_subdir}\\{seq.name}"')
        for event in seq.events:
            lines.append(f"\t{event}")
        if seq.fps is not None:
            fps = int(seq.fps) if seq.fps == int(seq.fps) else seq.fps
            lines.append(f"\tfps {fps}")
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


__all__ = ["QcSequence", "build_qc", "parse_sequences", "parse_attachments", "modelname"]
